services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
